fakeapi:
  base-url: https://jsonplaceholder.typicode.com/

publicholidayapi:
  base-url: https://date.nager.at/api/v3/publicholidays/


mail:
  email-to: ${EMAIL_TO}


spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_FROM}
    password: ${PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
